plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\mohdl\\affiliate-builder\\public"
publishOrigin = "ui"
commandOrigin = "ui"
command = "hugo"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]